name: Delivery
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GCP Import import.json
        run: |
          echo "${{ secrets.GOOGLE_IMPORT_CREDENTIALS }}" | base64 --decode > import.json
      - name: Install JSONquery package to export release data
        run: |
          echo "CLIENT_EMAIL=$(cat import.json | jq -r .client_email)" >> $GITHUB_ENV
          echo "RELEASE_PROJECT=$(cat import.json | jq -r .project_id)" >> $GITHUB_ENV
          echo "VERSION=$(cat VERSION.txt | sed -e 's/\./-/g')" >> $GITHUB_ENV
          echo "SHORT_COMMIT=$(echo ${{ github.event.pull_request.head.sha }} | cut -z -c1-10)" >> $GITHUB_ENV
      - name: Release image to definitive project
        run: |
          gcloud auth activate-service-account $CLIENT_EMAIL --key-file=import.json
          gcloud compute images create envoy-$VERSION-debian-11 \
          --source-image=envoy-$VERSION-$SHORT_COMMIT-debian-11 \
          --family="envoy-debian-11" \
          --labels version=$VERSION,type=release,commit=$GITHUB_SHA \
          --source-image-project="${{ secrets.WORKSPACE_PROJECT }}" \
          --project=$RELEASE_PROJECT
          gcloud compute images delete envoy-$VERSION-$SHORT_COMMIT-debian-11 --project="${{ secrets.WORKSPACE_PROJECT }}"
          gcloud auth revoke $CLIENT_EMAIL
          rm -f import.json